### ISSUE TITLE
'collections' has no attribute 'Iterable' in python > 3.10

### ISSUE THREAD

**Issue by wbalmer** [avigan/VLTPF#100]
Hi! I'm using the sphere tools to reduce some IRDIS data, and ran into this error on python v3.10 when running the sphere_dataset.py example. 

The full traceback is:

Traceback (most recent call last):
  File "/Users/wbalmer/SPHERE/dataset.py", line 25, in <module>
    ds.full_reduction()
  File "/opt/anaconda3/envs/sphere/lib/python3.10/site-packages/sphere/SPHERE.py", line 525, in full_reduction
    r.full_reduction()
  File "/opt/anaconda3/envs/sphere/lib/python3.10/site-packages/sphere/IRDIS/ImagingReduction.py", line 406, in full_reduction
    self.process_science()
  File "/opt/anaconda3/envs/sphere/lib/python3.10/site-packages/sphere/IRDIS/ImagingReduction.py", line 370, in process_science
    self.sph_ird_combine_data(cpix=config['combine_cpix'],
  File "/opt/anaconda3/envs/sphere/lib/python3.10/site-packages/sphere/IRDIS/ImagingReduction.py", line 1725, in sph_ird_combine_data
    nimg = imutils.shift(img, (cc-cx, cc-cy), method=shift_method)
  File "/opt/anaconda3/envs/sphere/lib/python3.10/site-packages/sphere/utils/imutils.py", line 150, in shift
    if isinstance(shift_value, collections.Iterable):
AttributeError: module 'collections' has no attribute 'Iterable'

It appears that the way to call `Iterable` in python > 3.9 is from `collections.abc` and changing that in lines 150 and 725 in utils/imutils.py cleared up the problem for me :)

**Comment by avigan** [comment]
Fixed with 1406c6bad7469bf93f59dedf6a40adb7e8773d52

Available in release v1.5.1.
