### ISSUE TITLE
Error in preprocessing of dataset

### ISSUE THREAD

**Issue by avigan** [avigan/VLTPF#59]
Salut Arthur!

J’ai un message d’erreur quand je fais tourner ton code. J’obtiens:

>>> dataset.full_reduction()

*
* Full IRDIS reduction at path /home/slacour/SPHERE/DATA/sphere_irdifs_HIP_32775_final.obx_id=200416257/2017-02-06/IRDIS/
*

Sorting raw files
 * found 39 FITS files in /home/slacour/SPHERE/DATA/sphere_irdifs_HIP_32775_final.obx_id=200416257/2017-02-06/IRDIS/raw/
Extracting frames information
Downloading http://maia.usno.navy.mil/ser7/finals2000A.all
|=============================================================================================================================================================================| 3.2M/3.2M (100.00%)         4s
 * Object:      HIP_32775
 * RA / DEC:    06:50:17.204 / -60:16:29.89
 * Date:        2017-02-07
 * Instrument:  IRDIS
 * Derotator:   ELEV
 * Coronagraph: N_ALC_YJH_S
 * Mode:        NIROBS
 * Filter:      BB_H
 * DIT:         16.00 sec
 * NDIT:        20
 * Texp:        85.33 min
 * PA:          -10.59° ==> 24.41° = 35.00°
 * POSANG:      0.00°
Performing file association for calibrations
 * Warning: there is no sky background for science files with DIT=8.0 sec. Using a sky background instead of an internal instrumental background can usually provide a cleaner data reduction, especially in K-band
There are 1 warning(s) and 0 error(s) in the classification of files
Creating darks and backgrounds
 * DARK in filter DB_Y23 with DIT=0.84 sec (2 files)
 * DARK,BACKGROUND in filter BB_H with DIT=16.00 sec (1 files)
 * DARK,BACKGROUND in filter DB_H23 with DIT=16.00 sec (1 files)
 * DARK,BACKGROUND in filter BB_H with DIT=8.00 sec (1 files)
 * SKY in filter BB_H with DIT=16.00 sec (3 files)
Creating flats
 * filter BB_H (10 files)
Pre-processing science files
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/slacour/SPHERE/pythonSoft/VLTPF/vltpf/SPHERE.py", line 456, in full_reduction
    r.full_reduction()
  File "/home/slacour/SPHERE/pythonSoft/VLTPF/vltpf/IRDIS/ImagingReduction.py", line 289, in full_reduction
    self.preprocess_science()
  File "/home/slacour/SPHERE/pythonSoft/VLTPF/vltpf/IRDIS/ImagingReduction.py", line 243, in preprocess_science
    collapse_center=config['preproc_collapse_center'])
  File "/home/slacour/SPHERE/pythonSoft/VLTPF/vltpf/IRDIS/ImagingReduction.py", line 951, in sph_ird_preprocess_science
    index = pd.MultiIndex(names=['FILE', 'IMG'], levels=[[], []], codes=[[], []])
  File "/usr/lib/python3/dist-packages/pandas/core/indexes/multi.py", line 118, in __new__
    raise TypeError("Must pass both levels and labels")
TypeError: Must pass both levels and labels
>>> 

Tu comprends d’où cela pourrait venir?

**Comment by avigan** [comment]
Salut,

Je vais regarder ça. C'est le même jeu de données pour lequel tu avais créé un ticket sur GitHub? J'ai téléchargé ce jeu de données, donc je vais regarder ça de plus près. Je crée un ticket sur GitHub pour garder un suivi.

Est-ce que tu pourrais m'envoyer un:

dfits *.fits | fitsort DATE-OBS ORIGFILE

sur la liste des fichiers que tu utilises? C'est pour être sûr que j'utilise les mêmes pour reproduire le bug.

**Comment by avigan** [comment]
Closing. Problem should be solved.
